#Question 1: What is CTR for google_wide campaign on February 1, 2021?

SELECT campaign_name , c_date , (clicks/impressions) as CTR
FROM marketing
WHERE campaign_name = 'google_wide'
    AND c_date = '2021-02-01';
    
#Question 2: What is Conversion 1 for instagram_tier2 campaign on February 5, 2021?

SELECT campaign_name, c_date , (leads/clicks) as Conversion_1
FROM marketing
WHERE campaign_name = 'instagram_tier2'
    AND c_date = '2021-02-05';

#Question 3: What is Conversion 2 for facebook_tier1 campaign on February 9, 2021?

SELECT campaign_name, c_date , (orders/leads) as Conversion_2
FROM marketing
WHERE campaign_name = 'facebook_tier1'
    AND c_date = '2021-02-09';

#Question 4: What is the total number of impressions for each campaign on February 1, 2021?

SELECT campaign_name, SUM(impressions) AS total_impressions
FROM marketing
WHERE c_date = '2021-02-01'
GROUP BY campaign_name;

#Question 5: What is the total amount spent on each campaign on February 1, 2021?

SELECT campaign_name, SUM(mark_spent) AS total_spent
FROM marketing
WHERE c_date = '2021-02-01'
GROUP BY campaign_name;

#Question 6: What is the total revenue generated by each campaign on February 1, 2021?

SELECT campaign_name, SUM(revenue) AS total_revenue
FROM marketing
WHERE c_date = '2021-02-01'
GROUP BY campaign_name;
